export const products = [
  {
    id: '1',
    title: 'Running Shoes',
    price: 99,
    image: '/shoe.jpg',
    description: 'High-performance running shoes for all terrains.',
    category: 'Footwear',
  },
  {
    id: '2',
    title: 'Wireless Smartwatch',
    price: 129,
    image: '/watch.jpg',
    description: 'Stylish smartwatch with health tracking features.',
    category: 'Electronics',
  },
  {
    id: '3',
    title: 'Backpack',
    price: 129,
    image: '/backpack.jpg',
    description: 'Durable and spacious backpack for everyday use.',
    category: 'Accessories',
  },
  {
    id: '4',
    title: 'Smartwatch',
    price: 249,
    image: '/watch.jpg',
    description: 'Feature-rich smartwatch with fitness tracking and notifications.',
    category: 'Accessories',
  },
  {
    id: '5',
    title: 'Sunglasses',
    price: 149,
    image: '/sunglass.jpg',
    description: 'UV-protected sunglasses with a modern design.',
    category: 'Accessories',
  },
  {
    id: '6',
    title: 'Digital Camera',
    price: 499,
    image: '/camera.jpg',
    description: 'High-resolution digital camera with 4K video recording.',
    category: 'Electronics',
  },
  {
    id: '7',
    title: 'T-shirt',
    price: 29,
    image: '/tshirt.png',
    description: 'Comfortable cotton t-shirt available in multiple colors.',
    category: 'Clothing',
  },
  
];
